spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/gerenboke?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1217
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis plus的mapper的xml文件的扫描路径
mybatis-plus:
  mapper-locations: classpath*:com/qj/mapper/*.xml
  type-aliases-package: com.qj.entity



#jwt token
# token有效时长，7天，单位秒
#  jwt:
#    EXPIRE_TIME: 7 * 24 * 60 * 60 * 1000
#    SECRET: $989Hdjy)_fa@

logging:
  level:
    com.qj: debug
